In [ ]:
import os
import requests
import pandas as pd
import duckdb
from datetime import datetime
from dotenv import load_dotenv ,find_dotenv

# 1. 환경 변수 로드
load_dotenv(find_dotenv)
API_KEY = os.getenv('OPINET_API_KEY')
MINIO_ENDPOINT = os.getenv('MINIO_ENDPOINT')
MINIO_ACCESS_KEY = os.getenv('MINIO_ACCESS_KEY')
MINIO_SECRET_KEY = os.getenv('MINIO_SECRET_KEY')

In [4]:
 #2. API 호출 - JSON 형식
url = f"https://www.opinet.co.kr/api/avgAllPrice.do?out=json&code={API_KEY}"

response = requests.get(url)
data = response.json()

print(data)

{'RESULT': {'OIL': [{'TRADE_DT': '20260123', 'PRODCD': 'B034', 'PRODNM': '고급휘발유', 'PRICE': '1931.84', 'DIFF': '-0.61'}, {'TRADE_DT': '20260123', 'PRODCD': 'B027', 'PRODNM': '휘발유', 'PRICE': '1692.80', 'DIFF': '-1.01'}, {'TRADE_DT': '20260123', 'PRODCD': 'D047', 'PRODNM': '자동차용경유', 'PRICE': '1585.94', 'DIFF': '-1.34'}, {'TRADE_DT': '20260123', 'PRODCD': 'C004', 'PRODNM': '실내등유', 'PRICE': '1319.37', 'DIFF': '-0.31'}, {'TRADE_DT': '20260123', 'PRODCD': 'K015', 'PRODNM': '자동차용부탄', 'PRICE': '997.99', 'DIFF': '-0.08'}]}}

In [5]:

# 3. 데이터프레임 변환
# 오피넷 응답 구조에 따라 data['RESULT']['OIL'] 형태일 수 있습니다.
df = pd.DataFrame(data['RESULT']['OIL'])

# 4. 데이터 가공 (수집시간 추가)
#df['collect_time'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
display(df)

   TRADE_DT PRODCD  PRODNM    PRICE   DIFF
0  20260123   B034   고급휘발유  1931.84  -0.61
1  20260123   B027     휘발유  1692.80  -1.01
2  20260123   D047  자동차용경유  1585.94  -1.34
3  20260123   C004    실내등유  1319.37  -0.31
4  20260123   K015  자동차용부탄   997.99  -0.08

In [7]:
 oil_list = data.get('RESULT', {}).get('OIL', [])
 df = pd.DataFrame(oil_list)
display(df)

   TRADE_DT PRODCD  PRODNM    PRICE   DIFF
0  20260123   B034   고급휘발유  1931.84  -0.61
1  20260123   B027     휘발유  1692.80  -1.01
2  20260123   D047  자동차용경유  1585.94  -1.34
3  20260123   C004    실내등유  1319.37  -0.31
4  20260123   K015  자동차용부탄   997.99  -0.08